[workspace]
members = [
    "ttlog",
    "ttlog-view",
    "examples/ttlog-simple",
    "examples/ttlog-server", 
    "examples/ttlog-complex",
    "examples/ttlog-filereader",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A comprehensive tracing and logging system"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/ttlog"

[workspace.dependencies]
# Add common dependencies here if needed 