[package]
name = "ttlog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["clock"] }
lz4 = "1.28.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.142"
crossbeam-channel = "0.5.15"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
use = "0.0.1-pre.0"
gethostname = "1.0.2"

